In [3]:
import numpy as np
# create a numpy array
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [21]:
# access single element
a1_zero = np.zeros((2, 3))
print(a1_zero) # 2D array of zeros with shape (2, 3)
a2_one_array = np.ones((3, 4))
print(a2_one_array) # 2D array of ones with shape (3, 4)
a3_full_array = np.full((2, 2), 7)
print(a3_full_array) # 2D array filled with 7s with shape (2, 2)
a4_eye = np.eye(3)
print(a4_eye) # 3x3 identity matrix
a5_random = np.random.rand(2, 3)
print(a5_random) # 2D array with random values between 0 and 1  

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[7 7]
 [7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.29744372 0.80170569 0.89746986]
 [0.92560421 0.73483292 0.57683226]]


In [17]:
# create a 1D array of zeros, ones, a range of numbers, and random numbers
arr1d = np.array([10, 20, 30, 40, 50])
# single element access
elem = arr1d[2]
print("Element at index 2:", elem) # Output: 30

Element at index 2: 30


In [18]:
# Create a 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# access element at row 1, column 2
elem_2d = arr2d[1, 2]
print("Element at row 1, column 2:", elem_2d) # Output: 6



Element at row 1, column 2: 6


In [19]:
# Multidimensional array access
arr3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
elem_3d = arr3d[1, 0, 1]
print("Element at [1, 0, 1]:", elem_3d)

Element at [1, 0, 1]: 6


In [20]:
# Slicing examples
slice_1d = arr1d[1:4]
print("Slice of 1D array from index 1 to 3:", slice_1d)
slice_2d = arr2d[0:2, 1:3]
print("Slice of 2D array rows 0-1 and columns 1-2:\n", slice_2d)

Slice of 1D array from index 1 to 3: [20 30 40]
Slice of 2D array rows 0-1 and columns 1-2:
 [[2 3]
 [5 6]]


In [23]:
# Boolean indexing
bool_idx = arr1d > 25
filtered_arr = arr1d[bool_idx]
print("Elements greater than 25 in arr1d:", filtered_arr)

Elements greater than 25 in arr1d: [30 40 50]


In [24]:
# Fancy indexing
fancy_idx = [0, 2, 4]
fancy_elements = arr1d[fancy_idx]
print("Elements at indices 0, 2, 4:", fancy_elements)

Elements at indices 0, 2, 4: [10 30 50]


In [25]:
# Modifying array elements
arr1d[0] = 99
print("Modified arr1d:", arr1d)
arr2d[1, 1] = 55
print("Modified arr2d:\n", arr2d)

Modified arr1d: [99 20 30 40 50]
Modified arr2d:
 [[ 1  2  3]
 [ 4 55  6]
 [ 7  8  9]]


In [26]:
# Using slicing to modify multiple elements
arr1d[1:3] = [88, 77]
print("Modified arr1d after slicing assignment:", arr1d)
arr2d[0:2, 0:2] = [[11, 22], [33, 44]]
print("Modified arr2d after slicing assignment:\n", arr2d)

Modified arr1d after slicing assignment: [99 88 77 40 50]
Modified arr2d after slicing assignment:
 [[11 22  3]
 [33 44  6]
 [ 7  8  9]]


In [27]:
# Boolean indexing to modify elements
arr1d[arr1d < 50] = 0
print("Modified arr1d after boolean indexing assignment:", arr1d)
arr2d[arr2d > 30] = 99
print("Modified arr2d after boolean indexing assignment:\n", arr2d)

Modified arr1d after boolean indexing assignment: [99 88 77  0 50]
Modified arr2d after boolean indexing assignment:
 [[11 22  3]
 [99 99  6]
 [ 7  8  9]]


In [29]:
# Fancy indexing to modify specific elements
arr1d[fancy_idx] = [1, 2, 3]
print("Modified arr1d after fancy indexing assignment:", arr1d)
arr2d[[0, 2], [1, 2]] = [7, 8]
print("Modified arr2d after fancy indexing assignment:\n", arr2d)

Modified arr1d after fancy indexing assignment: [ 1 88  2  0  3]
Modified arr2d after fancy indexing assignment:
 [[11  7  3]
 [99 99  6]
 [ 7  8  8]]


In [32]:
# Example array with both positive and negative values
arr = np.array([-3, -1, 0, 1, 3])
# Applying a unary operation: absolute value
result = np.absolute(arr)
print("Absolute value:", result)
# create an array of sine values
a = np.array([0, np.pi/2, np.pi])
sine_values = np.sin(a)
print("Sine values:", sine_values)
# create an array and compute its exponential
b = np.array([0, 1, 2])
exp_values = np.exp(b)
print("Exponential values:", exp_values)
# square root of an array
c = np.array([0, 1, 4, 9])
sqrt_values = np.sqrt(c)
print("Square root values:", sqrt_values)
# natural logarithm of an array
d = np.array([1, np.e, np.e**2])
log_values = np.log(d)
print("Natural logarithm values:", log_values)
# create two arrays for binary operations
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
# addition
add_result = np.add(x, y)
print("Addition result:", add_result)
# subtraction
sub_result = np.subtract(x, y)
print("Subtraction result:", sub_result)
# multiplication
mul_result = np.multiply(x, y)
print("Multiplication result:", mul_result)
# division
div_result = np.divide(x, y)
print("Division result:", div_result)

Absolute value: [3 1 0 1 3]
Sine values: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Exponential values: [1.         2.71828183 7.3890561 ]
Square root values: [0. 1. 2. 3.]
Natural logarithm values: [0. 1. 2.]
Addition result: [5 7 9]
Subtraction result: [-3 -3 -3]
Multiplication result: [ 4 10 18]
Division result: [0.25 0.4  0.5 ]


In [ ]:
# set alias names for dtypes
dtypes = [('name', 'S10'), ('grad_year', int), ('cgpa', float)]
# create an array with structured dtypes
students = np.array([(b'Alice', 2020, 3.5),
                     (b'Bob', 2019, 3.7),
                     (b'Charlie', 2021, 3.8)], dtype=dtypes)
print("Students array:", students)

Students array: [(b'Alice', 2020, 3.5) (b'Bob', 2019, 3.7) (b'Charlie', 2021, 3.8)]
